PROPN_NNPS lemmas -> no s
UniversalDependencies/UD_English-EWT pull request #149
Opened 2021-04-16 05:06 UTC by AngledLuffa

Addresses, at least partially, issue https://github.com/UniversalDependencies/UD_English-EWT/issues/147

2021-04-16 05:07 UTC, AngledLuffa commented
Also fixes a few demonyms which weren't in the original list I searched for

2021-04-16 13:28 UTC, nschneid commented on en_ewt-ud-dev.conllu
> +5	thr	thr	ADV	RB	Typo=Yes	4	advmod	4:advmod	CorrectForm=there
lemma = there

2021-04-16 13:29 UTC, nschneid commented on not-to-release/sources/answers/20111106022931AAwpqXm_ans.xml.conllu
> +1	NZers	NZer	PROPN	NNPS	Number=Plur	5	vocative	5:vocative	SpaceAfter=No
Abbr=Yes?

2021-04-17 00:18 UTC, AngledLuffa commented
Updated those changes, although obviously there's also a lot more
discussion going on.

2021-04-17 13:59 UTC, nschneid commented
I think there's a token of "democrat" and a token of "republican" that should be capitalized in the lemma.

2021-04-19 00:01 UTC, AngledLuffa commented
Done.

2021-04-19 01:15 UTC, nschneid commented
Excellent! Now how about updating to United/NNP States/NNPS? This is actually specified in the PTB tagging guidelines:

![image](https://user-images.githubusercontent.com/985263/115169097-1f3e3180-a08b-11eb-98d7-b96ae2c5c8dd.png)

2021-04-19 02:49 UTC, nschneid commented
Also Number=Plur

2021-04-19 05:13 UTC, AngledLuffa commented
Done

2021-04-24 04:44 UTC, nschneid commented on en_ewt-ud-train.conllu
> +8	Sports	Sport	PROPN	NNP	Number=Sing	9	compound	9:compound	_
NNPS, Number=Plur?

2021-04-24 05:13 UTC, AngledLuffa commented
Yep

2021-04-24 17:45 UTC, nschneid requested changes
Looked over a bunch. A lot of great improvements. Just a couple things:

1. Please use a script to ensure that NNPS == Number=Plur == form ends in -s but lemma doesn't. And NNP == Number=Sing. And PROPN == (NNP or NNPS). I think those are all correct assumptions for now.
2. I don't understand the policy for capitalizing PROPN lemmas of places/organizations where the form is lowercase. There seem to be inconsistencies, even for pluralized names at issue here. (I realize that standardizing this for non-pluralized names would be out of scope.)

2021-04-24 17:45 UTC, nschneid commented on not-to-release/sources/answers/20111107193044AAvUYBv_ans.xml.conllu
> +32	airlines	airline	PROPN	NNPS	Number=Plur	28	nmod	28:nmod:from	_
capitalize lemmas for both PROPNs?

2021-04-24 17:45 UTC, nschneid commented on not-to-release/sources/answers/20111107203006AA9ojw8_ans.xml.conllu
> +19	states	State	PROPN	NNPS	Number=Sing	16	obl	16:obl:to	SpaceAfter=No
Number=Plur

2021-04-24 17:45 UTC, nschneid commented on not-to-release/sources/answers/20111107221352AAlIioO_ans.xml.conllu
> +2	ribs	rib	PROPN	NNPS	Number=Plur	3	nsubj	3:nsubj	_
capitalize lemmas?

2021-04-24 17:45 UTC, nschneid commented on not-to-release/sources/answers/20111108085945AAgJhOG_ans.xml.conllu
> +7	pets	pet	PROPN	NNPS	Number=Plur	5	conj	5:conj:and	_
capitalize PROPN lemmas?

2021-04-24 17:45 UTC, nschneid commented on not-to-release/sources/answers/20111108093942AAYF9Dn_ans.xml.conllu
> +2	Roadways	Roadway	PROPN	NNP	Number=Sing	3	compound	3:compound	_
Number=Plur

2021-04-24 17:45 UTC, nschneid commented on not-to-release/sources/answers/20111108093942AAYF9Dn_ans.xml.conllu
> +2	Roadways	Roadway	PROPN	NNP	Number=Sing	3	compound	3:compound	_
and NNPS

2021-04-24 17:45 UTC, nschneid commented on not-to-release/sources/answers/20111108102205AArwNzY_ans.xml.conllu
> +9	states	State	PROPN	NNPS	Number=Sing	5	nmod	5:nmod:from	_
Number=Plur

2021-04-24 18:57 UTC, amir-zeldes commented
Just as a note, GUM does capitalize things like southwestern airlines -> Southwestern Airline:

https://corpling.uis.georgetown.edu/annis/#_q=eHBvcz0vTk5QLj8vIF89XyB0b2s9L1thLXpdKy8gXz1fIGxlbW1hPS9bQS1aXS4qLw&_c=R1VN&cl=5&cr=5&s=0&l=10

2021-04-24 20:52 UTC, AngledLuffa commented
I fixed each of the specific things you caught.

I did the following greps:

> NNPS == Number=Plur ...
> And NNP == Number=Sing

grep NNP * | grep "Number=Plur" | grep -v NNPS
grep NNPS * | grep "Number=Sing"

> PROPN == (NNP or NNPS)

grep PROPN * | grep -v NNP

This one turned up Central, which is tagged slightly inconsistently.  I see
no reason to consider Central Iowa a proper noun - I don't think this is a
county name or that the regions have specific names, although I could be
wrong.  Central Otago is in fact the name of a region in NZ.  What about
Central Intelligence Agency?  In cases such as North Vietnam, we label
North as PROPN/NNP, so I guess Central should also be PROPN/NNP?  That's
not a compelling argument to me, though.  There's also Central Asian
Republics, for which various words can be found capitalized if you search
online.

It also dredged up No. which I suppose should be labeled Abbr=Yes
everywhere.

Modern China?  modern as the lemma with ADJ/JJ as the tag?  This specific
example is part of a book title

> NNPS == Number=Plur == form ends in -s

Disagree...  plural nouns don't necessarily end in s.  People, for
example.  Although the exceptions are pretty few and can be checked by hand.

egrep "[a-rt-zA-RT-Z]  [a-zA-Z]+       PROPN   NNPS" *
(those are tab characters, not spaces)

Is the lemma of People person?  What if it's a collective noun, such as The
People vs EWT?

What is the tag on Chinese instead of Chinese people?  It sounds like a
noun to me, but perhaps it's an adjective with a hidden noun.

> ... but lemma doesn't

grep "s        PROPN   NNPS" *
As we've been over, there's a whole lot of exceptions.  Falls, Beatles,
Valdes, ... Mathematics?  I suggest punting on this and making a new issue
if needed


On Sat, Apr 24, 2021 at 10:45 AM Nathan Schneider ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Looked over a bunch. A lot of great improvements. Just a couple things:
>
>    1. Please use a script to ensure that NNPS == Number=Plur == form ends
>    in -s but lemma doesn't. And NNP == Number=Sing. And PROPN == (NNP or
>    NNPS). I think those are all correct assumptions for now.
>    2. I don't understand the policy for capitalizing PROPN lemmas of
>    places/organizations where the form is lowercase. There seem to be
>    inconsistencies, even for pluralized names at issue here. (I realize that
>    standardizing this for non-pluralized names would be out of scope.)
>
> ------------------------------
>
> In not-to-release/sources/answers/20111107193044AAvUYBv_ans.xml.conllu
> <https://github.com/UniversalDependencies/UD_English-EWT/pull/149#discussion_r619686469>
> :
>
> > @@ -85,7 +85,7 @@
>  29	mail	mail	X	NN	Number=Sing	28	goeswith	28:goeswith	_
>  30	from	from	ADP	IN	_	32	case	32:case	_
>  31	southwest	southwest	PROPN	NNP	Number=Sing	32	compound	32:compound	_
> -32	airlines	airlines	PROPN	NNPS	Number=Plur	28	nmod	28:nmod:from	_
> +32	airlines	airline	PROPN	NNPS	Number=Plur	28	nmod	28:nmod:from	_
>
> capitalize lemmas for both PROPNs?
> ------------------------------
>
> In not-to-release/sources/answers/20111107203006AA9ojw8_ans.xml.conllu
> <https://github.com/UniversalDependencies/UD_English-EWT/pull/149#discussion_r619686487>
> :
>
> > @@ -34,7 +34,7 @@
>  16	back	back	ADV	RB	_	15	advmod	15:advmod	_
>  17	to	to	ADP	IN	_	19	case	19:case	_
>  18	the	the	DET	DT	Definite=Def|PronType=Art	19	det	19:det	_
> -19	states	states	PROPN	NNP	Number=Sing	16	obl	16:obl:to	SpaceAfter=No
> +19	states	State	PROPN	NNPS	Number=Sing	16	obl	16:obl:to	SpaceAfter=No
>
> Number=Plur
> ------------------------------
>
> In not-to-release/sources/answers/20111107221352AAlIioO_ans.xml.conllu
> <https://github.com/UniversalDependencies/UD_English-EWT/pull/149#discussion_r619686519>
> :
>
> > @@ -130,7 +130,7 @@
>  # sent_id = answers-20111107221352AAlIioO_ans-0009
>  # text = prime ribs have very good food but its super expensive
>  1	prime	prime	PROPN	NNP	Number=Sing	2	compound	2:compound	_
> -2	ribs	ribs	PROPN	NNPS	Number=Plur	3	nsubj	3:nsubj	_
> +2	ribs	rib	PROPN	NNPS	Number=Plur	3	nsubj	3:nsubj	_
>
> capitalize lemmas?
> ------------------------------
>
> In not-to-release/sources/answers/20111108085945AAgJhOG_ans.xml.conllu
> <https://github.com/UniversalDependencies/UD_English-EWT/pull/149#discussion_r619686599>
> :
>
> > @@ -236,7 +236,7 @@
>  4	s	's	PART	POS	_	3	case	3:case	_
>  5	aquarium	aquarium	PROPN	NNP	Number=Sing	0	root	0:root	_
>  6	and	and	CCONJ	CC	_	7	cc	7:cc	_
> -7	pets	pets	PROPN	NNPS	Number=Plur	5	conj	5:conj:and	_
> +7	pets	pet	PROPN	NNPS	Number=Plur	5	conj	5:conj:and	_
>
> capitalize PROPN lemmas?
> ------------------------------
>
> In not-to-release/sources/answers/20111108093942AAYF9Dn_ans.xml.conllu
> <https://github.com/UniversalDependencies/UD_English-EWT/pull/149#discussion_r619686719>
> :
>
> > @@ -21,7 +21,7 @@
>  # newpar id = answers-20111108093942AAYF9Dn_ans-p0002
>  # text = UP Roadways buses ply frequently between Sector-37 crossing in Noida and Kasna in Greater Noida, passing through Pari Chowk.
>  1	UP	UP	PROPN	NNP	Number=Sing	2	compound	2:compound	_
> -2	Roadways	Roadways	PROPN	NNP	Number=Sing	3	compound	3:compound	_
> +2	Roadways	Roadway	PROPN	NNP	Number=Sing	3	compound	3:compound	_
>
> Number=Plur
> ------------------------------
>
> In not-to-release/sources/answers/20111108102205AArwNzY_ans.xml.conllu
> <https://github.com/UniversalDependencies/UD_English-EWT/pull/149#discussion_r619686785>
> :
>
> > @@ -176,7 +176,7 @@
>  6	here	here	ADV	RB	PronType=Dem	5	advmod	5:advmod	_
>  7	from	from	ADP	IN	_	9	case	9:case	_
>  8	the	the	DET	DT	Definite=Def|PronType=Art	9	det	9:det	_
> -9	states	states	PROPN	NNP	Number=Sing	5	nmod	5:nmod:from	_
> +9	states	State	PROPN	NNPS	Number=Sing	5	nmod	5:nmod:from	_
>
> Number=Plur
> ------------------------------
>
> In not-to-release/sources/answers/20111108093942AAYF9Dn_ans.xml.conllu
> <https://github.com/UniversalDependencies/UD_English-EWT/pull/149#discussion_r619686723>
> :
>
> > @@ -21,7 +21,7 @@
>  # newpar id = answers-20111108093942AAYF9Dn_ans-p0002
>  # text = UP Roadways buses ply frequently between Sector-37 crossing in Noida and Kasna in Greater Noida, passing through Pari Chowk.
>  1	UP	UP	PROPN	NNP	Number=Sing	2	compound	2:compound	_
> -2	Roadways	Roadways	PROPN	NNP	Number=Sing	3	compound	3:compound	_
> +2	Roadways	Roadway	PROPN	NNP	Number=Sing	3	compound	3:compound	_
>
> and NNPS
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/UniversalDependencies/UD_English-EWT/pull/149#pullrequestreview-644052037>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2AYWLLDXMP2EJP4AHY2JDTKL7U5ANCNFSM43AZHUWA>
> .
>

2021-04-24 21:19 UTC, nschneid commented
Central Intelligence Agency: Central/PROPN is fine for now. (We'll revisit tagging of adjectives in names separately. I was mainly concerned about lowercase forms in plural names being given uppercase lemmas only some of the time.)

As in WordNet, it should be people/people/Sing if referring to a specific body (a people) and people/person/Plur otherwise. I would say the former applies to the political uses and the latter to "Highly Effective People".

If Chinese heads a noun phrase, e.g. "I had Chinese last night" (implicit: food), I would guess it should be PROPN.

2021-04-24 21:28 UTC, AngledLuffa commented
Now the Electoral Commission is refusing to punish people for mere past
Baath Party membership.

--- person?

 They are setting the road blocks at the exact same positions they were
during the war last year, which indicates they are the same people

--- person as well?

 people who are suggesting that we go out and fight them are living in
dream land.

--- also sounds like person

Pakistan People's Party

--- People?  people?

 the people of Pakistan

--- people?  although it's tagged NNS in the treebank

Actually this is becoming really tedious.  Suggest opening a separate issue
for this as well instead of fixing it in this changelist

On Sat, Apr 24, 2021 at 2:19 PM Nathan Schneider ***@***.***>
wrote:

> Central Intelligence Agency: Central/PROPN is fine for now. (We'll revisit
> tagging of adjectives in names separately. I was mainly concerned about
> lowercase forms in plural names being given uppercase lemmas only some of
> the time.)
>
> As in WordNet, it should be people/people/Sing if referring to a specific
> body (a people) and people/person/Plur otherwise. I would say the former
> applies to the political uses and the latter to "Highly Effective People".
>
> If Chinese heads a noun phrase, e.g. "I had Chinese last night" (implicit:
> food), I would guess it should be PROPN.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/UniversalDependencies/UD_English-EWT/pull/149#issuecomment-826155000>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2AYWJSTKBQC5UHXCADGVLTKMYXVANCNFSM43AZHUWA>
> .
>

2021-04-24 21:30 UTC, nschneid commented
> Actually this is becoming really tedious. 

Yeah I would limit this PR to proper names.

2021-04-24 21:31 UTC, nschneid commented on en_ewt-ud-train.conllu
> +28	series	Series	PROPN	NNP	Number=Plur	23	nmod	23:nmod:of	SpaceAfter=No
Number=Sing

2021-04-24 21:34 UTC, nschneid commented on en_ewt-ud-train.conllu
> +5	bush	Bush	PROPN	NNP	Number=Plur	7	nmod:poss	7:nmod:poss	_
Number=Sing

2021-04-24 21:34 UTC, nschneid commented on en_ewt-ud-train.conllu
> +18	Devil	Devil	PROPN	NNP	Number=Plur	22	nmod:poss	22:nmod:poss	_
Number=Sing

2021-04-24 21:35 UTC, nschneid commented on en_ewt-ud-train.conllu
> +44	mcallister	McAllister	PROPN	NNP	Number=Plur	46	nmod:poss	46:nmod:poss	_
Number=Sing

2021-04-24 21:36 UTC, nschneid commented on en_ewt-ud-train.conllu
> +46	deli	Deli	PROPN	NNPS	Number=Plur	41	acl:relcl	41:acl:relcl	_
NNP, Number=Sing?

2021-04-24 22:15 UTC, merged

2021-04-25 15:29 UTC, amir-zeldes commented
> As in WordNet, it should be people/people/Sing if referring to a specific body (a people) and people/person/Plur otherwise. I would say the former applies to the political uses and the latter to "Highly Effective People".

FYI in GUM it has been people -> people regardless of sense and number, treating person/persons as a separate lemma. Aside from WordNet is there a lemmatized corpus precedent advocating people -> person?

2021-04-25 15:44 UTC, nschneid commented
I don't know about lemmatization practices in corpora that don't follow WordNet but it's certainly the case that when we want to pluralize "person" we usually say "people"—"persons" is restricted to certain genres.

2021-04-25 15:53 UTC, amir-zeldes commented
OK, I can match that in GUM too